# Generated by Django 3.1.5 on 2021-01-17 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='userDetail',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('income', models.FloatField()),
                ('current_balance', models.FloatField()),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_name', models.CharField(max_length=1000)),
                ('transaction_type', models.CharField(choices=[('0', 'Deposite'), ('1', 'Withdrawal')], max_length=10)),
                ('transaction_amaount', models.FloatField()),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
