# Generated by Django 3.1.5 on 2021-01-17 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_amaount',
            new_name='transaction_amount',
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_time',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
